### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by HGL2533** [jiangzhongshi/bijective-projection-shell#13]
hi! 
The code for the tests module needs to be built separately? Following your instructions from FigureScripts, I built the project and [100%] Built target breve_bin, but the following error occurred: "error: array bound is not an integer constant before ‘]’ token" on line 4032 | static char altStackMem[4 * SIGSTKSZ]; and "error: ‘altStackMem’ was not declared in this scope" on line 4051 | sigStack.ss_sp = altStackMem;.

**Comment by jiangzhongshi** [comment]
Hey,
the code you quoted does not seem too familiar to me, do you know which file you are refering to?
```
static char altStackMem
```
